# -*- coding: utf-8 -*-
"""GridPACK Data Analysis with CuDF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgjf0lgZmPDZmWZ2Oe9geNd2b_JbgW9P
"""

!pip install -q cudf-cu12 dask-cudf-cu12 matplotlib pandas

from google.colab import drive
drive.mount("/content/drive")

import dask_cudf
import matplotlib.pyplot as plt

MERGED_FILE = "/content/drive/MyDrive/merged_branches_with_area.parquet"
PARTITIONED_OUT = "/content/drive/MyDrive/merged_branches_partitioned"

cols = [
    "contingency",
    "from_bus",
    "to_bus",
    "circuit_id",
    "loading_percent",
    "from_area",
    "from_area_name",
    "to_area",
    "to_area_name",
]

ddf = dask_cudf.read_parquet(
    MERGED_FILE,
    columns=cols,
    split_row_groups=True,
    blocksize="64MB",
)

ddf = ddf.repartition(npartitions=200)

ddf.to_parquet(
    PARTITIONED_OUT,
    write_index=False,
    compression="snappy",
    write_metadata_file=False,
)

ddf = dask_cudf.read_parquet(
    "/content/drive/MyDrive/merged_branches_partitioned",
    columns=cols,
    split_row_groups=True,
    blocksize="64MB",
)

print("Partitions:", ddf.npartitions)

def normalize_columns(ddf):
    return ddf.assign(
        overloaded=ddf.loading_percent >= 100.0
    )

ddf = normalize_columns(ddf)

# Persist once since every later function uses these columns
ddf = ddf.persist()

#grouping functions
def group_by_branch(ddf):
    """
    Groups by physical branch using numeric columns.
    Faster than grouping by string branch_id.
    """
    return (
        ddf.groupby(["from_bus", "to_bus", "circuit_id"])
        .agg({
            "contingency": "count",
            "overloaded": "sum",
            "loading_percent": "max",
            "from_area_name": "first",
            "to_area_name": "first",
        })
        .rename(columns={
            "contingency": "num_contingencies",
            "overloaded": "num_overloads",
            "loading_percent": "max_loading_pct",
        })
        .reset_index()
    )


def group_by_from_area(ddf):
    return (
        ddf.groupby("from_area_name")
        .agg({
            "contingency": "count",
            "overloaded": "sum",
            "loading_percent": "max",
        })
        .rename(columns={
            "contingency": "num_records",
            "overloaded": "num_overloads",
            "loading_percent": "max_loading_pct",
        })
        .reset_index()
    )


def group_by_area_pair(ddf):
    return (
        ddf.groupby(["from_area_name", "to_area_name"])
        .agg({
            "contingency": "count",
            "overloaded": "sum",
            "loading_percent": "max",
        })
        .rename(columns={
            "contingency": "num_records",
            "overloaded": "num_overloads",
            "loading_percent": "max_loading_pct",
        })
        .reset_index()
    )


def group_by_contingency(ddf):
    return (
        ddf.groupby("contingency")
        .agg({
            "overloaded": "sum",
            "loading_percent": "max",
        })
        .rename(columns={
            "overloaded": "num_overloaded_branches",
            "loading_percent": "max_loading_pct",
        })
        .reset_index()
    )

def filter_overloaded(ddf):
    return ddf[ddf.overloaded]


def filter_loading_threshold(ddf, threshold=100):
    return ddf[ddf.loading_percent >= threshold]


def filter_by_from_area(ddf, area_name):
    return ddf[ddf.from_area_name == area_name]


def filter_by_to_area(ddf, area_name):
    return ddf[ddf.to_area_name == area_name]


def filter_by_area(ddf, area_name):
    return ddf[
        (ddf.from_area_name == area_name) |
        (ddf.to_area_name == area_name)
    ]


def filter_by_area_pair(ddf, from_area, to_area):
    return ddf[
        (ddf.from_area_name == from_area) &
        (ddf.to_area_name == to_area)
    ]


def filter_by_contingency(ddf, contingency):
    return ddf[ddf.contingency == contingency]

def top_branches_by_loading(ddf, n=20):
    branch_summary = group_by_branch(ddf)
    return branch_summary.nlargest(n, "max_loading_pct")


def top_branches_by_overloads(ddf, n=20):
    branch_summary = group_by_branch(ddf)
    return branch_summary.nlargest(n, "num_overloads")


def top_areas_by_overloads(ddf, n=20):
    area_summary = group_by_from_area(ddf)
    return area_summary.nlargest(n, "num_overloads")


def top_area_pairs_by_overloads(ddf, n=20):
    area_pair_summary = group_by_area_pair(ddf)
    return area_pair_summary.nlargest(n, "num_overloads")


def top_contingencies_by_overloads(ddf, n=20):
    contingency_summary = group_by_contingency(ddf)
    return contingency_summary.nlargest(n, "num_overloaded_branches")

def plot_bar(pdf, x_col, y_col, title, xlabel, ylabel):
    pdf = pdf.to_pandas() if hasattr(pdf, "to_pandas") else pdf

    plt.figure(figsize=(10, 6))
    plt.barh(pdf[x_col].astype(str), pdf[y_col])
    plt.gca().invert_yaxis()
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.tight_layout()
    plt.show()

area_summary = group_by_from_area(ddf)

top_areas = (
    area_summary
    .nlargest(25, "max_loading_pct")
    .compute()
    .to_pandas()
)

top_areas = top_areas.sort_values("max_loading_pct", ascending=True)

plt.figure(figsize=(12, 9))

plt.barh(
    top_areas["from_area_name"],
    top_areas["max_loading_pct"]
)

plt.axvline(
    x=30,
    linestyle="--",
    linewidth=1.5,
    label="Underutilization Threshold (30%)"
)

for i, value in enumerate(top_areas["max_loading_pct"]):
    plt.text(
        value + 0.4,
        i,
        f"{value:.1f}%",
        va="center",
        fontsize=9
    )

plt.title("Ranking of Transmission Utilization by Control Area")
plt.xlabel("Maximum Line Utilization (%)")
plt.ylabel("Control Area")
plt.legend()
plt.grid(axis="x", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()